sources:
  - name: MotoMotaGP
    handler:
      mysql:
        # You can use environment variables like
        # host: "{env.MYSQL_HOST}"
        # port: "{env.MYSQL_PORT}"
        # user: "{env.MYSQL_USER}"
        # password: "{env.MYSQL_PASSWORD}"
        # database: "{env.MYSQL_DATABASE}"
        host: motomotagp-db.cwhlsfwtpidd.eu-west-1.rds.amazonaws.com
        port: 3306
        user: admin
        password: PwyTAaH5TU
        database: my_motomotagp